- src/introduction/simulation/A1042.java
修改 `  for (int i = 1; i < N; i++) ` 为 `  for (int i = 1; i <= N; i++) ` ,导致输出的时候无法输出最后一个元素
> [fix wrong] 修改PAT - A1042 中的错误

- src/introduction/simulation/A1042.java
> [Bug] 修改 A1042.java 中的错误代码

- csource/PAT-B1018C语言解法
> PAT-B1018C语言解法

- PAT/javaSrc/A1042.java
- PAT/javaSrc/B1001.java
- PAT/javaSrc/B1008.java
- PAT/javaSrc/B1011.java
- PAT/javaSrc/B1012.java
- PAT/javaSrc/B1016.java
- PAT/javaSrc/B1018.java
- PAT/javaSrc/B1046.java
> delete java package name

- PAT/cSrc/PAT-B1010(c).cpp
> [Solution] 提交PAT_B1010.一元多项式求导的C语言解法

- PAT/cSrc/PAT-B1041(c).cpp
> [Solution] 提交PAT_B1041.考试座位号的C语言解法

- PAT/cSrc/PAT-B1004 成绩排名.cpp
根据 #69 ，提交 PAT-B1004.成绩排名的 C++ 解法
> [Solution] 提交PAT_B1004.成绩排名的 CPP 语言解法

- PAT/javaSrc/PAT-B1004.java
> [Solution] 提交PAT_B1004.成绩排名的java语言解法

- .github/ISSUE_TEMPLATE/issue.md
> [Add Workflow]

- PAT/cSrc/PAT-B1028 人口普查.cpp
> [Solution] 提交PAT_B1028 人口普查的 c++ 语言解法 

- PAT/javaSrc/PAT-B1028.java
> [Solution] 提交PAT_B1028 人口普查的 java 语言解法

- PAT/cSrc/PAT-B1032 挖掘机技术哪家强.cpp
>  [Solution] 提交PAT-B1032 挖掘机技术哪家强 的 C++ 语言解法

- PAT/javaSrc/PAT-B1032.挖掘机技术哪家强.java
根据现有issue 提交相关解法[#90](https://github.com/OS-EDU/KO--CSP/issues/90)
> [Solution] 提交PAT-B1032 挖掘机技术哪家强 的 java 语言解法 

- PAT/cSrc/PAT-B1022.D进制的A+B.cpp
> [Solution] 提交PAT-B1022.D 进制的 A + B 的 C++ 语言解法

- PAT/javaSrc/PAT-B1022.java
提交PAT-B1022.D 进制的 A + B 的 java 语言解法
> [Solution] 提交PAT-B1022.D 进制的 A + B 的 java 语言解法

- PAT/javaSrc/PAT-B1030.完美数列.java
> [Solution] 提交PAT-B1030.完美数列 的 java 语言解法

- PAT/cSrc/PAT-B1030 完美数列.cpp
> [Solution] 提交PAT-B1030.完美数列 的 C++ 语言解法

- PAT/cSrc/PAT-B1036 跟奥巴马一起编程.cpp
根据 #104 ，提交 PAT-B1036.跟奥巴马一起编程 C++ 语言解法
> [Solution] 提交PAT-B1036.跟奥巴马一起编程 的 C++ 语言解法

- PAT/javaSrc/PAT-B1009.说反话(1).java
- PAT/javaSrc/PAT-B1009.说反话(2).java
> [Solution] 提交PAT-B1009.说反话 的 Java 语言解法

- PAT/javaSrc/PAT-B1036.和奥巴马一起编程.java
根据 [#104 ](https://github.com/OS-EDU/KO--CSP/issues/104) ，提交 PAT-B1036.跟奥巴马一起编程 Java 语言解法
> [Solution] 提交PAT-B1036.跟奥巴马一起编程 的 Java 语言解法

- PAT/cSrc/PAT-B1013.数素数01.cpp
- PAT/cSrc/PAT-B1013.数素数02.cpp
> [Solution] 提交PAT-B1013数素数 的 C++ 语言解法

- PAT/javaSrc/PAT-B1013.数素数.java
> [Solution] 提交PAT-B1013.数素数 的 java 语言解法

- PAT/cSrc/PAT-B1007素数对猜想.cpp
> [Solution] PAT-B1007素数对猜想 C++ 解法

- .github/hypertrons.json
import an auto robot to manage the project
> [Improvement] [Enhancement]Create hypertrons.json

- .github/hypertrons.json
> [Improvement] Update hypertrons.json

- PAT/javaSrc/PAT-B1027.打印沙漏.java
---
name: PR
about: Template of solutions
title: "[Solution] 提交PAT-B1027.打印沙漏 的 java 语言解法"
labels: Solution
assignees: freedom3219
---
> [Solution] 提交PAT-B1027.打印沙漏 的 java 语言解法

- PAT/cSrc/PAT-B1027.打印沙漏.cpp
增加 PAT-B1027.打印沙漏 C++ 解法
---
name: PAT-B1027.打印沙漏
about: Template of solutions
title: "[Solution] 提交PAT-B1027.打印沙漏 的 C++ 语言解法"
labels: status/pending
assignees:  @QuakeWang 
---
* [相关链接（建议）]：Issue  #131 
* [题目信息（必选）]：PAT-B1027.打印沙漏
* [题解思路（可选）]：
> [Solution] 提交PAT-B1027.打印沙漏 的 C++ 语言解法

- PAT/cSrc/PAT-A1046.ShortestDistance.cpp
---
name: PAT-A1046.Shortest Distance 
about: 提交 PAT-A1046 C++ 解法
title: "[Solution] 提交 PAT-A1046 Shortest Distance "
labels: solution、PAT-A、C++
assignees: @QuakeWang 
---
* [相关链接（建议）]：Issue #42
> [Solution] PAT-A1046.Shortest Distance C++ 解法

- PAT/javaSrc/PAT-A1046.Shortest Distance.java
---
name: PAT-A1046.Shortest Distance 
about: 提交 PAT-A1046 Java 解法
title: "[Solution] 提交 PAT-A1046 Shortest Distance "
labels: solution、PAT-A、Java
---
* [相关链接（建议）]：Issue #42
> [Solution] PAT-A1046.Shortest Distance Java 解法

- PAT/javaSrc/PAT-B1002.写出这个数.java
---
name: PAT-B1002.写出这个数
about: 提交 PAT-B1002.写出这个数 Java 解法
title: "[Solution] 提交 PAT-B1002.写出这个数 "
---
* [相关链接（建议）]：Issue #154
> [Solution] PAT-B1002.写出这个数 Java 解法

- PAT/javaSrc/PAT-B1006.换个格式输出整数.java
---
name: PAT-B1006.换个格式输出整数
about: 提交 PAT-B1006.换个格式输出整数 Java 解法
title: "[Solution] 提交 PAT-B1006.换个格式输出整数 "
---
* [相关链接（建议）]：Issue #154
> [Solution] PAT-B1006.换个格式输出整数 Java 解法

- PAT/javaSrc/PAT-B1005.继续(3n+1)猜想.java
---
name: PAT-B1005.继续(3n+1)猜想
about: 提交 PAT-B1005.继续(3n+1)猜想 Java 解法
title: "[Solution] 提交 PAT-B1005.继续(3n+1)猜想 "
---
* [相关链接（建议）]：Issue #154
> [Solution] PAT-B1005.继续(3n+1)猜想 Java 解法

- PAT/javaSrc/PAT-B1014.福尔摩斯的约会.java
---
name: PAT-B1014.福尔摩斯的约会
about: 提交 PAT-B1014.福尔摩斯的约会 Java 解法
title: "[Solution] 提交 PAT-B1014.福尔摩斯的约会 "
---
* [相关链接（建议）]：Issue  [#133](https://github.com/OS-EDU/KO--CSP/issues/133)
* [题目信息（必选）]：https://pintia.cn/problem-sets/994805260223102976/problems/994805308755394560
* [题解思路（可选）]：
> [Solution] PAT-B1014.福尔摩斯的约会 Java 解法

- PAT/javaSrc/PAT-B1003.我要通过！.java
---
name: PAT-B1003.我要通过！
about: 提交 PAT-B1003.我要通过！ Java 解法
title: "[Solution] 提交 PAT-B1003.我要通过！ "
---
* [相关链接（建议）]：Issue  [#133](https://github.com/OS-EDU/KO--CSP/issues/133)
* [题目信息（必选）]：https://pintia.cn/problem-sets/994805260223102976/problems/994805323154440192
* [题解思路（可选）]：
> [Solution] PAT-B1003.我要通过！ Java 解法

- PAT/javaSrc/PAT-B1015.德才论.java
---
name: PAT-B1015.德才论
about: 提交 PAT-B1015.德才论 Java 解法
title: "[Solution] 提交 PAT-B1015.德才论 "
---
* [相关链接（建议）]：Issue  [#133](https://github.com/OS-EDU/KO--CSP/issues/133)
* [题目信息（必选）]：https://pintia.cn/problem-sets/994805260223102976/problems/994805307551629312
* [题解思路（可选）]：
> [Solution] PAT-B1015.德才论 Java 解法

- PAT/cSrc/PAT-B1015.德才论.cpp
---
name: PAT-B1015.德才论
about: Template of solutions
title: "[Solution] PAT-B1015.德才论 C++ 解法"
labels: C++、PAT-B、Solution
assignees: @QuakeWang 
---
* [相关链接（建议）]：Issue #177 
* [题目信息（必选）]：[PAT-B1015.德才论.md](https://github.com/OS-EDU/KO--CSP/blob/main/PAT/%E9%A2%98%E7%9B%AE%E6%8F%8F%E8%BF%B0/PAT-B1015.%E5%BE%B7%E6%89%8D%E8%AE%BA.md)
* [题解思路（可选）]：
> [Solution] PAT-B1015.德才论 C++ 解法

- PAT/cSrc/PAT-A1042.ShufflingMachine.cpp
> PAT-A1042.ShufflingMachine.cpp edited

- PAT/cSrc/PAT-B1023.组个最小数.cpp
提交 PAT-B1023 C++ 解法
---
name:  PAT-B1023.组个最小数
about: Template of solutions
title: "[Solution]  PAT-B1023.组个最小数"
labels: solution、pat-b、c++
assignees: @JaydenHD 
---
* [相关链接（建议）]：Issue #209 
* [题目信息（必选）]：
* [题解思路（可选）]：
> [Solution]提交 PAT-B1023.组个最小数 C++ 解法

- PAT/javaSrc/PAT-B1001.害死人不偿命的(3n+1)猜想.java
> [Improvement] Fix PAT-B1001.害死人不偿命的(3n+1)猜想.java
